benchmarks:
  octane-benchmark:
    dependencies:
    - base
    - criterion ==1.1.*
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Game
default-extensions:
- DeriveGeneric
- OverloadedLabels
- TemplateHaskell
description: Octane parses Rocket League replays.
executables:
  octane:
    dependencies:
    - base
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- data/*.json
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
library:
  dependencies:
  - aeson >=0.11 && <1.1
  - base ==4.9.*
  - bimap ==0.3.*
  - binary ==0.8.*
  - binary-bits ==0.5.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-binary-ieee754 ==0.4.*
  - data-default-class ==0.0.*
  - deepseq ==1.4.*
  - file-embed ==0.0.*
  - http-client >=0.4.30 && <0.6
  - http-client-tls >=0.2 && <0.4
  - overloaded-records ==0.4.*
  - regex-compat ==0.95.*
  - text ==1.2.*
  - unordered-containers ==0.2.*
  - vector ==0.11.*
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: octane
synopsis: Parse Rocket League replays.
tests:
  octane-doctest:
    dependencies:
    - base
    - octane
    - doctest ==0.11.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DocTest.hs
    source-dirs: test-suite
  octane-test-suite:
    dependencies:
    - base
    - octane
    - tasty ==0.11.*
    - tasty-hspec ==1.1.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.13.4'
