name: octane
version: 0.20.2

category: Game
description: Octane parses Rocket League replays.
extra-source-files:
  - CHANGELOG.markdown
  - data/*.json
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/octane
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
synopsis: Parse Rocket League replays.

dependencies:
  - aeson >=0.11 && <1.3
  - base >=4.9 && <4.11
  - bimap ==0.3.*
  - binary ==0.8.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-default-class <0.2
  - file-embed ==0.0.*
  - overloaded-records ==0.4.*
  - rattletrap ==3.*
  - text ==1.2.*
ghc-options:
  - -Wall

library:
  other-modules: Paths_octane
  source-dirs: library

executables:
  octane:
    dependencies:
      - http-client >=0.4.30 && <0.6
      - http-client-tls >=0.2 && <0.4
      - octane
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: executable
